### ISSUE TITLE
An issue where only raw files are created when run with "Attribute patch-level 2 or 3"

### ISSUE THREAD

**Issue by wanchae** [AICAN-Research/FAST-Pathology#49]
When deploying with patch-level 2 or 3, only "segmentation.raw" file is created instead of segmentation.tiff. 

In the fastpathology screen, low resolution segmentation overlays are made well.  Please see the link below for photos.
[https://forum.image.sc/t/question-about-converting-fastpathology-segmentation-file-for-importing-to-qupath/72855](url)

Thank you so much,

Seoung Wan Chae.

**Comment by andreped** [comment]
@wanchae This has been discussed in a separate Issue https://github.com/AICAN-Research/FAST-Pathology/issues/45.

What happened was that when the generated segmentation got too small, instead of storing it in a pyramidal format (TIFF) it was stored as .mhd/.raw. This has been fixed in FAST and will be made available in the next upcoming release of FastPathology.

We might be able to provide a new release by the end of the week. Will keep you updated :]

**Comment by andreped** [comment]
@wanchae assuming you are on Windows, you could try downloading and installing the latest artefact which is made available here: https://github.com/AICAN-Research/FAST-Pathology/actions/runs/3210898280

You need to be logged into GitHub to artefact. The file should be named: `Windows package`.

Alternatively, try clicking this link, which should download the installer for you directly: [Windows package](https://github.com/AICAN-Research/FAST-Pathology/suites/8679933854/artifacts/391159732)

If I remember correctly, the issue you had should have been resolved in this artefact.

**Comment by smistad** [comment]
No @andreped, the fix has not been added yet. It is a bug in FP, not in FAST.

**Comment by andreped** [comment]
> No @andreped, the fix has not been added yet. It is a bug in FP, not in FAST.

Huh? I thought this issue was due to FAST having special handling of small segmentation images, where these images were stored in mhd/raw instead of pyramidal TIFFs. But this was fixed in FAST either right after the summer vacation, AFAIK. Hence, now all segmentations should be stored in the same pyramidal TIFF format. However, for smaller segmentation images, there should only be a single image plane, no? But that should not be an issue. Or is there something that is missing in FP?

What needs changing in FP for this to work?

**Comment by wanchae** [comment]
I have confirmed that it has been corrected the issue. It works perfectly. Thank you very much.
<img width="817" alt="Import_Anno_LR_seg_from_FP" src="https://user-images.githubusercontent.com/116047503/196843216-39a7bc17-45d9-4b2a-9c1c-ca576ea4243d.png">

**Comment by smistad** [comment]
Thanks for the feedback @wanchae
